#!/bin/bash

RED='\033[0;31m'
YELLOW='\033[0;33m'
NOCOLOR='\033[0m'

black --check network_hash_gen/

if [ $? != 0 ]; then
	printf "${RED}aborting commit due to incomplete formatting.${NOCOLOR}\n"
	exit 1
fi

python -m unittest discover

if [ $? != 0 ]; then
	printf "${RED}aborting commit because unittests failed.${NOCOLOR}\n"
	exit 1
fi
